### ISSUE TITLE
Issues and Feedback from course

### ISSUE THREAD

**Issue by Henrik-KM** [softmatterlab/DeepTrack2#139]
1. Get deeptrack working through conda

2. Missing dependencies, i.e. tensorflow_datasets and opencv. Start from a clean version of deeptrack and see which packages give errors (and fix them)

**Comment by BenjaminMidtvedt** [comment]
1. I guess I'm fighting a losing battle of getting people to stop using conda haha. I will look into it.
2. cv2 is not a dependency of deeptrack. tensorflow_datasets is, and I'm not sure how it wasn't added. I have corrected. We always test from a clean version of deeptrack, everytime we do a pull request. However, it pulls from requirements.txt instead of setup.py, which can have slight differences in dependencies.

**Comment by BenjaminMidtvedt** [comment]
I can update it so that they match exactly. I didn't want to initially, because our doc pages have some extra dependencies that the general user will not need. However I suppose I can remove those explicitly instead
